### RECIPE INDEX
GET http://localhost:3000/photos.json

### RECIPE CREATE
POST http://localhost:3000/photos.json
Content-Type: application/json

{

}

### RECIPE SHOW
GET http://localhost:3000/photos/1.json

### RECIPE UPDATE
PATCH http://localhost:3000/photos/1.json
Content-Type: application/json

{

}

### RECIPE DESTROY
DELETE http://localhost:3000/photos/1.json